#!/bin/bash

# Current Version: 1.0.3

## How to get and use?
# git clone "https://github.com/hezhijie0327/Toolkit.git" && bash ./Toolkit/Git.sh -u "hezhijie0327" -e "hezhijie0327@hotmail.com" -f "." -r "Toolkit" -i "Generated by GitHub Actions" -m "push"

## Parameter
while getopts e:f:i:m:r:u: GetParameter; do
    case ${GetParameter} in
        e) USER_EMAIL="${OPTARG}";;
        f) COMMIT_FILE="${OPTARG}";;
        i) COMMIT_INFO="${OPTARG}";;
        m) GIT_MODE="${OPTARG}";;
        r) REPO_NAME="${OPTARG}";;
        u) USER_NAME="${OPTARG}";;
    esac
done

## Function
# Check Configuration Validity
function CheckConfigurationValidity() {
    if [ "${USER_EMAIL}" == "" ]; then
        echo "An error occurred during processing. Missing (USER_EMAIL) value, please check it and try again."
        exit 1
    elif [ "$(echo ${USER_EMAIL} | grep '@')" == "" ]; then
        echo "An error occurred during processing. Invalid (USER_EMAIL) value, please check it and try again."
        exit 1
    fi
    if [ "${COMMIT_FILE}" == "" ]; then
        echo "An error occurred during processing. Missing (COMMIT_FILE) value, please check it and try again."
        exit 1
    fi
    if [ "${COMMIT_INFO}" == "" ]; then
        echo "An error occurred during processing. Missing (COMMIT_INFO) value, please check it and try again."
        exit 1
    fi
    if [ "${GIT_MODE}" == "" ]; then
        echo "An error occurred during processing. Missing (GIT_MODE) value, please check it and try again."
        exit 1
    elif [ "${GIT_MODE}" != "push" ]; then
        echo "An error occurred during processing. Invalid (GIT_MODE) value, please check it and try again."
        exit 1
    fi
    if [ "${REPO_NAME}" == "" ]; then
        echo "An error occurred during processing. Missing (REPO_NAME) value, please check it and try again."
        exit 1
    fi
    if [ "${USER_NAME}" == "" ]; then
        echo "An error occurred during processing. Missing (USER_NAME) value, please check it and try again."
        exit 1
    fi
}
# Check Requirement
function CheckRequirement() {
    which "git" > "/dev/null" 2>&1
    if [ "$?" -eq "1" ]; then
        echo "git is not existed."
        exit 1
    fi
}

## Process
# Call CheckConfigurationValidity
CheckConfigurationValidity
# Call CheckRequirement
CheckRequirement
if [ "${GIT_MODE}" == "push" ]; then
    if [ "$(git status -s)" == "" ]; then
        echo "Oops! ${USER_NAME}/${REPO_NAME} has no changes."
    else
        git config user.name "${USER_NAME}"
        git config user.email "${USER_EMAIL}"
        git add "${COMMIT_FILE}"
        git commit -m "${COMMIT_INFO}"
        git push --force
        if [ "$?" -eq "0" ]; then
            echo "Congratulations! ${USER_NAME}/${REPO_NAME} has pushed successfully."
        else
            echo "Oops! ${USER_NAME}/${REPO_NAME} has not pushed successfully."
        fi
    fi
fi
